FROM  nginx:1.23.3-alpine

COPY ./default.conf /etc/nginx/conf.d/default.conf

# We wrote the Dockerfile because, we needed the nginx:1.23.3-alpine image alsong with the config file default.cong to run the nginx container.
