FROM  nginx:1.23.3-alpine

COPY ./default.conf /etc/nginx/conf.d/default.conf

# We wrote the Dockerfile because, we needed the nginx:1.23.3-alpine image alsong with copying the config file default.conf inside the container to run the nginx container.
